import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AOSInit } from './aos'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CrystalMediatech",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
  openGraph: {
    title: "CrystalMediatech",
    description: "Your website description",
    url: "https://www.yourwebsite.com",
    images: [
      {
        url: "/favicon.ico",
        width: 800,
        height: 600,
        alt: "CrystalMediatech Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@yourtwitterhandle",
    creator: "@yourtwitterhandle",
    title: "CrystalMediatech",
    description: "Your website description",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={inter.className}>
        <div className="bg-[#000309]">
          <Header />
        </div>
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
